import { FormSubmit } from "@/components/admin/form-submit";
import { AdminPageHeader } from "@/components/admin/page-header";
import { updateSiteVisitAction } from "@/lib/actions/admin";
import { getAdminSiteVisits } from "@/lib/data/admin";

type Props = { searchParams: Promise<{ status?: string }> };

export default async function AdminSiteVisitsPage({ searchParams }: Props) {
  const { status = "all" } = await searchParams;
  const visits = await getAdminSiteVisits(status);
  return <><AdminPageHeader eyebrow="Lead management" title="Site visits" description="Requests remain pending until a representative explicitly confirms availability." /><form className="mb-6 flex gap-3 border border-deep-olive/12 bg-soft-cream p-4"><select name="status" defaultValue={status} className="form-control max-w-xs"><option value="all">All statuses</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button className="min-h-12 bg-deep-olive px-5 text-xs font-bold text-soft-cream uppercase">Apply</button></form>{visits.length ? <div className="grid gap-4">{visits.map((visit) => <details key={visit.id} className="border border-deep-olive/12 bg-soft-cream"><summary className="cursor-pointer list-none p-5"><div className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-center"><div><h2 className="font-heading text-2xl text-charcoal">{visit.full_name}</h2><p className="mt-1 text-xs text-charcoal/45">{visit.projects?.name ?? "Project unavailable"} · {visit.preferred_date} at {visit.preferred_time}</p></div><span className="justify-self-start border border-deep-olive/15 px-2.5 py-1 text-[0.62rem] font-bold tracking-[0.1em] text-deep-olive uppercase sm:justify-self-end">{visit.status}</span></div></summary><div className="border-t border-deep-olive/10 p-5"><dl className="grid gap-5 text-sm sm:grid-cols-4"><Info label="Phone" value={visit.phone} /><Info label="Email" value={visit.email ?? "Not provided"} /><Info label="Visitors" value={visit.visitor_count?.toString() ?? "Not provided"} /><Info label="Received" value={new Date(visit.created_at).toLocaleString("en")} /></dl>{visit.message ? <div className="mt-6 border-l-2 border-champagne-gold bg-warm-ivory/45 p-5 text-sm leading-7 text-charcoal/75 whitespace-pre-wrap">{visit.message}</div> : null}<form action={updateSiteVisitAction.bind(null, visit.id)} className="mt-6 grid gap-5"><div className="grid gap-5 sm:grid-cols-[0.4fr_1fr]"><label className="grid gap-2 text-xs font-bold text-charcoal uppercase"><span>Status</span><select name="status" defaultValue={visit.status} className="form-control"><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label className="grid gap-2 text-xs font-bold text-charcoal uppercase"><span>Private notes</span><textarea name="privateNotes" defaultValue={visit.private_notes ?? ""} rows={4} className="form-control resize-y" /></label></div><FormSubmit className="justify-self-start">Update request</FormSubmit></form></div></details>)}</div> : <div className="border border-deep-olive/12 bg-soft-cream px-6 py-16 text-center text-sm text-charcoal/50">No site-visit requests match this view.</div>}</>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-[0.62rem] font-bold tracking-[0.1em] text-charcoal/45 uppercase">{label}</dt><dd className="mt-1 text-charcoal">{value}</dd></div>; }
