"use client";

import { useActionState } from "react";

import { FormSubmit } from "@/components/admin/form-submit";
import { saveSettingsAction, type AdminActionState } from "@/lib/actions/admin";
import type { SiteSettings } from "@/types/domain";

export function SettingsForm({ settings }: { settings: SiteSettings }) {
  const [state, action] = useActionState(saveSettingsAction, { status: "idle", message: "" } satisfies AdminActionState);
  return (
    <form action={action} className="grid gap-7">
      <Panel title="Brand and company copy"><div className="grid gap-5 sm:grid-cols-2"><Field label="Company name"><input name="companyName" required defaultValue={settings.company_name} className="form-control" /></Field><Field label="Business descriptor"><input name="businessDescriptor" required defaultValue={settings.business_descriptor} className="form-control" /></Field></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Primary tagline"><input name="primaryTagline" required defaultValue={settings.primary_tagline} className="form-control" /></Field><Field label="Supporting statement"><input name="supportingStatement" required defaultValue={settings.supporting_statement} className="form-control" /></Field></div><Field label="Company introduction"><textarea name="companyIntroduction" required minLength={40} defaultValue={settings.company_introduction} rows={6} className="form-control resize-y" /></Field><div className="grid gap-5 lg:grid-cols-2"><Field label="Mission" hint="Leave blank until the wording is approved; blank copy stays hidden publicly."><textarea name="mission" defaultValue={settings.mission} rows={5} className="form-control resize-y" /></Field><Field label="Vision" hint="Leave blank until the wording is approved; blank copy stays hidden publicly."><textarea name="vision" defaultValue={settings.vision} rows={5} className="form-control resize-y" /></Field></div><Field label="Footer description"><textarea name="footerDescription" required defaultValue={settings.footer_description} rows={3} className="form-control resize-y" /></Field></Panel>

      <Panel title="Verified contact details" description="Leave a field empty until the official information has been confirmed. Empty fields stay hidden publicly."><div className="grid gap-5 sm:grid-cols-2"><Field label="Phone"><input name="phone" defaultValue={settings.phone ?? ""} className="form-control" /></Field><Field label="WhatsApp (international format)"><input name="whatsapp" defaultValue={settings.whatsapp ?? ""} placeholder="e.g. +92…" className="form-control" /></Field></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Email"><input name="email" type="email" defaultValue={settings.email ?? ""} className="form-control" /></Field><Field label="Business hours"><input name="businessHours" defaultValue={settings.business_hours ?? ""} className="form-control" /></Field></div><Field label="Office address"><textarea name="officeAddress" defaultValue={settings.office_address ?? ""} rows={3} className="form-control resize-y" /></Field><Field label="Verified Google Maps URL"><input name="mapUrl" type="url" defaultValue={settings.map_url ?? ""} className="form-control" /></Field></Panel>

      <Panel title="Social links"><div className="grid gap-5 lg:grid-cols-3"><Field label="Facebook URL"><input name="facebookUrl" type="url" defaultValue={settings.facebook_url ?? ""} className="form-control" /></Field><Field label="Instagram URL"><input name="instagramUrl" type="url" defaultValue={settings.instagram_url ?? ""} className="form-control" /></Field><Field label="LinkedIn URL"><input name="linkedinUrl" type="url" defaultValue={settings.linkedin_url ?? ""} className="form-control" /></Field></div></Panel>

      <Panel title="Homepage and search"><Field label="Announcement" hint="Leave empty to show the three business divisions instead."><input name="announcement" defaultValue={settings.announcement ?? ""} maxLength={240} className="form-control" /></Field><Field label="Default SEO title"><input name="defaultSeoTitle" required defaultValue={settings.default_seo_title} className="form-control" /></Field><Field label="Default SEO description"><textarea name="defaultSeoDescription" required defaultValue={settings.default_seo_description} rows={3} className="form-control resize-y" /></Field></Panel>

      <Panel title="Verified statistics" description="One per line in Value | Label format. Do not add estimates or placeholders."><Field label="Statistics"><textarea name="statistics" defaultValue={settings.statistics.map((item) => `${item.value} | ${item.label}`).join("\n")} rows={6} placeholder="25 | Verified projects" className="form-control resize-y" /></Field><label className="flex items-center gap-3 text-xs font-bold text-charcoal"><input name="showStatistics" type="checkbox" defaultChecked={settings.show_statistics} className="h-4 w-4 accent-deep-olive" />Show statistics section publicly</label></Panel>

      {state.message ? <p role="status" className={state.status === "success" ? "border-l-2 border-deep-olive pl-4 text-sm text-deep-olive" : "border-l-2 border-red-700 pl-4 text-sm text-red-700"}>{state.message}</p> : null}
      <div className="sticky bottom-4 z-20 border border-deep-olive/12 bg-soft-cream/95 p-3 shadow-[0_18px_45px_rgb(39_41_37/0.16)] backdrop-blur"><FormSubmit pendingLabel="Saving settings…">Save site settings</FormSubmit></div>
    </form>
  );
}

function Panel({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="border border-deep-olive/12 bg-soft-cream p-5 sm:p-7"><div className="mb-6 border-b border-deep-olive/10 pb-5"><h2 className="font-heading text-2xl text-charcoal">{title}</h2>{description ? <p className="mt-2 text-xs leading-6 text-charcoal/50">{description}</p> : null}</div><div className="grid gap-5">{children}</div></section>; }
function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className="grid gap-2 text-xs font-bold tracking-[0.07em] text-charcoal uppercase"><span>{label}</span>{children}{hint ? <span className="font-medium tracking-normal text-charcoal/45 normal-case">{hint}</span> : null}</label>; }
