"use client";

import { useActionState } from "react";

import { ConfirmSubmit } from "@/components/admin/confirm-submit";
import { FormSubmit } from "@/components/admin/form-submit";
import { deleteTestimonialAction, saveTestimonialAction, type AdminActionState } from "@/lib/actions/admin";
import type { Testimonial } from "@/types/domain";

export function TestimonialForm({ testimonial }: { testimonial?: Testimonial }) {
  const [state, action] = useActionState(saveTestimonialAction, { status: "idle", message: "" } satisfies AdminActionState);
  return <div className="border border-deep-olive/12 bg-soft-cream"><details open={!testimonial}><summary className="cursor-pointer list-none px-5 py-5"><div className="flex items-center justify-between gap-4"><div><h2 className="font-heading text-2xl text-charcoal">{testimonial?.client_name ?? "Add a verified testimonial"}</h2><p className="mt-1 text-xs text-charcoal/45">{testimonial ? `${testimonial.approved ? "Approved" : "Hidden"} · Verified ${new Date(testimonial.verified_at).toLocaleDateString("en")}` : "Do not add unverified or placeholder quotes"}</p></div><span className="text-xs font-bold tracking-[0.08em] text-deep-olive uppercase">Edit</span></div></summary><form action={action} className="grid gap-5 border-t border-deep-olive/10 p-5"><input type="hidden" name="id" value={testimonial?.id ?? ""} /><div className="grid gap-5 sm:grid-cols-2"><Field label="Client name"><input name="clientName" required defaultValue={testimonial?.client_name ?? ""} className="form-control" /></Field><Field label="Context (optional)"><input name="clientContext" defaultValue={testimonial?.client_context ?? ""} className="form-control" /></Field></div><Field label="Verified quote"><textarea name="quote" required minLength={20} maxLength={1200} defaultValue={testimonial?.quote ?? ""} rows={6} className="form-control resize-y" /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Display order"><input name="sortOrder" type="number" min="0" defaultValue={testimonial?.sort_order ?? 0} className="form-control" /></Field><label className="flex items-center gap-3 self-end pb-4 text-xs font-bold text-charcoal"><input name="approved" type="checkbox" defaultChecked={testimonial?.approved ?? false} className="h-4 w-4 accent-deep-olive" />Approved for public display</label></div>{state.message ? <p role="status" className={state.status === "success" ? "text-sm text-deep-olive" : "text-sm text-red-700"}>{state.message}</p> : null}<div className="flex flex-wrap gap-3"><FormSubmit>{testimonial ? "Save testimonial" : "Add testimonial"}</FormSubmit>{testimonial ? <ConfirmSubmit formAction={deleteTestimonialAction.bind(null, testimonial.id)} message={`Delete the testimonial from ${testimonial.client_name}?`} className="min-h-11 border border-red-700/25 px-4 text-xs font-bold text-red-700">Delete</ConfirmSubmit> : null}</div></form></details></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-xs font-bold tracking-[0.07em] text-charcoal uppercase"><span>{label}</span>{children}</label>; }
